/**
 * Generate the helper table (object format §10) from the runtime source: the
 * module the compiler carries, `ref/compile/helper-table.ts`, and the
 * published table in docs/helper-table.md. Each helper's ordinal, calling
 * convention and version come from its `@blob` line; its size from the built
 * library; its stack figures from the static analysis (tools/stack.ts).
 *
 * Usage: deno task helpers
 */
import { buildLibrary, type BuiltLibrary } from "./brl.ts";
import {
  CONSOLE_FILE,
  IO_ERROR_MEMBERS,
  PREDECLARED_CONSTANTS,
  PRINTER_FILE,
  SERVICES,
} from "../ref/compile/helpers.ts";

const BEGIN = "<!-- generated by tools/helpertable.ts: begin -->";
const END = "<!-- generated by tools/helpertable.ts: end -->";
const ROOT = new URL("../", import.meta.url).pathname;
export const MODULE = `${ROOT}ref/compile/helper-table.ts`;
export const DOC = `${ROOT}docs/helper-table.md`;
export const NATIVE = `${ROOT}native/compiler/HELPERS.ASM`;
export const NAMES = `${ROOT}native/compiler/PREDEF.ASM`;

/**
 * The register helpers the native compiler calls, by blob name, with the
 * ATOM names their equates take in native/compiler/HELPERS.ASM (D44: at
 * most eight characters, AREA_WHAT).
 */
export const NATIVE_NAMES: Record<string, string> = {
  RETN: "HP_RETN",
  STK_CHK: "HP_STACK",
  TRAP_BND: "HP_BOUND",
  TRAP_NAR: "HP_TRUNC",
  TRAP_LOO: "HP_LOOP",
  MUL16: "HP_MUL16",
  DIV16: "HP_DIV16",
  DIV16S: "HP_SDIV",
  ADD32: "HP_LADD",
  SUB32: "HP_LSUB",
  CMP32U: "HP_LCMPU",
  CMP32S: "HP_LCMPS",
  NEG32: "HP_LNEG",
  MUL32: "HP_LMUL",
  DIV32U: "HP_LDIVU",
  DIV32S: "HP_LDIVS",
  AND32: "HP_LAND",
  OR32: "HP_LOR",
  XOR32: "HP_LXOR",
  SHL32: "HP_LSHL",
  SHR32U: "HP_LSHRU",
  SHR32S: "HP_LSHRS",
  TRAP_AST: "HP_ASSRT",
  STR_SETL: "HP_SETL",
  FADD: "HP_FADD",
  FSUB: "HP_FSUB",
  FMUL: "HP_FMUL",
  FDIV: "HP_FDIV",
  FCMP: "HP_FCMP",
  I2F: "HP_ITOF",
  U2F: "HP_UTOF",
  F2I: "HP_FTOI",
  F2U: "HP_FTOU",
  TRAP_POO: "HP_PFULL",
  POOL_TRY: "HP_PTRY",
  POOL_DEL: "HP_PDEL",
  OBJ_FREE: "HP_OFREE",
  ID_CHK: "HP_IDCHK",
  ID_TEST: "HP_IDTST",
  OWN_SET: "HP_OWN",
  OWN_SETC: "HP_OWNC",
  LINK0: "HP_LINK0",
  ID_MAKE: "HP_IDMK",
  TRAP_CYC: "HP_CYCLE",
};

const hex = (n: number, width: number) =>
  "$" + n.toString(16).toUpperCase().padStart(width, "0");

/** Build the CPM22 runtime library as the compiler's table describes it. */
export async function buildRuntime(): Promise<BuiltLibrary> {
  const source = await Deno.readTextFile(`${ROOT}runtime/cpm22/cpm22.asm`);
  return await buildLibrary(
    source,
    `${ROOT}build/helper-table`,
    `${ROOT}runtime/cpm22`,
  );
}

/** The source of ref/compile/helper-table.ts. */
export function helperModule(built: BuiltLibrary): string {
  const rows = built.helpers.map((h) =>
    `  [${
      hex(h.ordinal, 3).replace("$", "0x").toLowerCase()
    }, "${h.name}", ${h.convention}, ${h.since}, ${h.returning}, ${h.ending}],`
  );
  return [
    "// Generated by tools/helpertable.ts from runtime/cpm22: do not edit.",
    "// Run `deno task helpers` after changing a helper.",
    "",
    "/** The helper-table version the compiler is built for. */",
    `export const HELPER_VERSION = ${built.helperVersion};`,
    "",
    "/** The interface key of each version, 1 up to HELPER_VERSION. */",
    `export const HELPER_KEYS: readonly number[] = [${
      built.helperKeys.map((k) => hex(k, 4).replace("$", "0x").toLowerCase())
        .join(", ")
    }];`,
    "",
    "export type HelperFigures = {",
    "  ordinal: number;",
    "  name: string;",
    "  /** 1: a service called with arguments on the stack; 2: a register helper. */",
    "  convention: number;",
    "  since: number;",
    "  /** Stack bytes a returning call uses, its return address included. */",
    "  stack: number;",
    "  /** Stack bytes any path uses, one that ends the program included. */",
    "  endingStack: number;",
    "};",
    "",
    "/** [ordinal, name, convention, since, stack, ending stack] */",
    "const ROWS: [number, string, number, number, number, number][] = [",
    ...rows,
    "];",
    "",
    "export const HELPER_TABLE: readonly HelperFigures[] = ROWS.map((",
    "  [ordinal, name, convention, since, stack, endingStack],",
    ") => ({ ordinal, name, convention, since, stack, endingStack }));",
    "",
  ].join("\n");
}

/**
 * The source of native/compiler/HELPERS.ASM: an equate for each helper of
 * NATIVE_NAMES whose low byte is its ordinal and whose high byte is its
 * stack figure, the two inline bytes EM_HELP and EM_JPH read after their
 * CALL; a trap site takes the low byte alone.
 */
export function nativeHelpers(built: BuiltLibrary): string {
  const rows = Object.entries(NATIVE_NAMES).map(([blob, name]) => {
    const h = built.helpers.find((x) => x.name === blob);
    if (!h) throw new Error(`no helper ${blob}`);
    if (h.convention !== 2 || h.ordinal > 0xff || h.returning > 0xff) {
      throw new Error(`${blob} is not a register helper below $100`);
    }
    const value = hex(h.returning * 256 + h.ordinal, 4);
    const left = `${name} EQU  ${value}`.padEnd(31);
    return `${left}; ${blob}: ordinal ${
      hex(h.ordinal, 2)
    }, ${h.returning} bytes of stack.`;
  });
  return [
    ";==========================================================================",
    ";  Runtime helpers",
    ";==========================================================================",
    ";",
    ";  Generated by tools/helpertable.ts from runtime/cpm22: do not edit; run",
    ";  `deno task helpers` after changing a helper. The ordinal and stack",
    ";  figure of each runtime helper the code generators call, from the",
    ";  helper table the reference compiler carries (object format section",
    ";  10). Each equate is a word: the ordinal in its low byte, the stack",
    ";  figure (the bytes a returning call uses, its return address",
    ";  included) in its high byte. EM_HELP and EM_JPH read it as the word",
    ";  after their CALL; a trap site (EM_TRAP) takes the ordinal alone.",
    ";  HP_VER and HP_KEY are the helper-table version the compiler is built",
    ";  for and that version's interface key, which the directory header",
    ";  carries and the library's key table must hold (section 10).",
    "",
    ...rows,
    `HP_VER EQU  ${built.helperVersion}`.padEnd(31) +
    "; The helper-table version compiled in.",
    `HP_KEY EQU  ${hex(built.helperKeys[built.helperVersion - 1], 4)}`.padEnd(
      31,
    ) + "; Its interface key.",
    "",
  ].join("\n");
}

/** The native type ID of a service's parameter or result type. */
function nativeType(type: string, isVar: boolean): string {
  const ids: Record<string, string> = {
    u8: "SY_U8",
    u16: "SY_U16",
    u32: "SY_U32",
    boolean: "SY_BOOL",
    File: "AG_FILE",
    "u8[]": isVar ? "AG_BUF+AG_VAR" : "AG_BUF",
    "string[]": isVar ? "AG_VIEW+AG_VAR" : "AG_VIEW",
  };
  const id = ids[type];
  if (!id) throw new Error(`no native type for ${type}`);
  return id;
}

/** Bytes an argument of a native type takes on the stack. */
const argumentBytes = (id: string) =>
  id.startsWith("SY_") && id !== "SY_U32" ? 2 : 4;

/**
 * The source of native/compiler/PREDEF.ASM: the names the compiler
 * predeclares (spec chapter 16), as ref/compile/helpers.ts gives them.
 * Each entry is the name as a length and spelling, then its payload. A
 * constant's is two bytes: SY_KNOWN with its type (SY_EXACT, or AG_FILE
 * for console and printer), then its value. A service's is laid out as a
 * routine record from RO_RTYPE (CALLWORK.ASM), whose first byte, its
 * result type, has bit 7 clear: its result type, its flags (RO_FFAIL),
 * its ordinal, its stack figure and its argument bytes; then the count
 * and native type IDs of its parameters.
 */
export function nativeNames(built: BuiltLibrary): string {
  const lines: string[] = [];
  const row = (code: string, comment: string) =>
    lines.push(`${`    ${code}`.padEnd(35)}; ${comment}`);
  let count = 0;
  for (const [name, value] of PREDECLARED_CONSTANTS) {
    row(`DB   ${name.length},"${name}"`, `${name}: a constant,`);
    row(`DB   SY_KNOWN+SY_EXACT,${value}`, `exact, ${value}.`);
    count += 1;
  }
  for (
    const [name, value] of [["console", CONSOLE_FILE], [
      "printer",
      PRINTER_FILE,
    ]] as const
  ) {
    row(`DB   ${name.length},"${name}"`, `${name}: a constant,`);
    row(
      `DB   SY_KNOWN+AG_FILE,${value}`,
      `the File the runtime fixes as ${value}.`,
    );
    count += 1;
  }
  for (const s of SERVICES) {
    const m = s.signature.match(
      /^sub (\w+)\(([^)]*)\)(?:: (\S+))?( fails IoError)?$/,
    );
    if (!m) throw new Error(`unparsed signature ${s.signature}`);
    const params = m[2] === "" ? [] : m[2].split(", ").map((p) => {
      const q = p.match(/^(var )?\w+: (\S+)$/);
      if (!q) throw new Error(`unparsed parameter ${p}`);
      return { type: q[2], isVar: q[1] !== undefined };
    });
    const ids = params.map((p) => nativeType(p.type, p.isVar));
    const result = m[3] === undefined ? "0" : nativeType(m[3], false);
    const flags = m[4] ? "RO_FFAIL+RO_FSVC" : "0";
    const h = built.helpers.find((x) => x.ordinal === s.ordinal);
    if (!h || h.convention !== 1 || h.returning > 0xff) {
      throw new Error(`${s.name} is not a service below 256 bytes of stack`);
    }
    const args = params.reduce(
      (n, p) => n + argumentBytes(nativeType(p.type, p.isVar)),
      0,
    );
    row(
      `DB   ${s.name.length},"${s.name}"`,
      `${s.name}: service ${hex(s.ordinal, 3)}.`,
    );
    row(
      `DB   ${result},${flags}`,
      `${m[3] ? `Result ${m[3]}` : "No result"}${m[4] ? "; it can fail" : ""}.`,
    );
    row(
      `DW   ${hex(s.ordinal, 3)},${h.returning}`,
      `Ordinal ${hex(s.ordinal, 3)}, ${h.returning} bytes of stack.`,
    );
    row(
      `DB   ${[args, ids.length, ...ids].join(",")}`,
      `${args} argument bytes; ${
        ids.length === 0
          ? "no parameters"
          : ids.length === 1
          ? "one parameter"
          : `${ids.length} parameters`
      }.`,
    );
    count += 1;
  }
  // IoError, the services' failure domain (D54): its members' spellings,
  // run together in ordinal order. PREP makes their nodes, taking their
  // lengths from IOERRS.ASM (ioErrorLengths).
  const io: string[] = ["HP_IOS:"];
  IO_ERROR_MEMBERS.forEach((name, i) => {
    io.push(`${`    DB   "${name}"`.padEnd(35)}; Member ${i}.`);
  });
  return [
    ";==========================================================================",
    ";  Predeclared names",
    ";==========================================================================",
    ";",
    ";  Generated by tools/helpertable.ts from ref/compile/helpers.ts and",
    ";  runtime/cpm22: do not edit; run `deno task helpers` after changing a",
    ";  service. The names every program sees before its own (spec chapter",
    ";  16): the error and mode constants, the console and printer, and the",
    ";  services with their signatures, ordinals and stack figures, from the",
    ";  helper table (object format section 10). RO_LIB searches HP_NAMES.",
    ";",
    ";  An entry is a length byte and the name's spelling, then its payload.",
    ";  A constant's is two bytes: SY_KNOWN with its type, SY_EXACT or",
    ";  AG_FILE, then its value. A service's is laid out as a routine record",
    ";  from RO_RTYPE (CALLWORK.ASM), so that RO_CALL reads both alike, and",
    ";  its first byte has bit 7 clear: its result type, its flags",
    ";  (RO_FFAIL), its ordinal, its stack figure (the bytes a returning call",
    ";  uses) and its argument bytes; then the count and the type IDs of its",
    ";  parameters.",
    ";  A zero length byte ends the table.",
    ";",
    ";  The table is the NAMES overlay of BASIE.OVL (OVERLAY.ASM), at the",
    ";  overlay area's start, where it stays for the whole compilation. It",
    ";  begins with the address of IoError's member spellings (D54), the",
    ";  HP_SKIP bytes that PREP reads (PP_RUN) and RO_LIB passes over.",
    "",
    `${"    DW   HP_IOS".padEnd(35)}; Where IoError's member spellings start.`,
    "HP_NAMES:",
    ...lines,
    `${`    DB   0`.padEnd(35)}; The end of the table: ${count} names.`,
    "",
    ...io,
    "",
  ].join("\n");
}

export const IOERRS = `${ROOT}native/compiler/IOERRS.ASM`;

/**
 * The source of native/compiler/IOERRS.ASM, part of the PREP overlay: the
 * length of each IoError member's spelling, in ordinal order, which PREP
 * pairs with the spellings in NAMES (PREDEF.ASM) to make the members' nodes.
 */
export function ioErrorLengths(): string {
  return [
    ";==========================================================================",
    ";  IoError's member lengths",
    ";==========================================================================",
    ";",
    ";  Generated by tools/helpertable.ts from ref/compile/helpers.ts: do not",
    ";  edit. The length of each member's spelling of IoError (D54), in",
    ";  ordinal order; NAMES holds the spellings themselves (HP_IOS).",
    "",
    "IO_LENS:",
    ...IO_ERROR_MEMBERS.map((name, i) =>
      `${`    DB   ${name.length}`.padEnd(35)}; ${i}: ${name}.`
    ),
    `IO_COUNT EQU  ${IO_ERROR_MEMBERS.length}`.padEnd(31) + "; Its members.",
    "",
  ].join("\n");
}

/** The generated section of docs/helper-table.md. */
export function helperTables(
  built: BuiltLibrary,
  basieNames: Map<number, string>,
): string {
  const out = [
    BEGIN,
    "",
    `Helper-table version ${built.helperVersion}; interface keys ${
      built.helperKeys.map((k, i) => `v${i + 1} ${hex(k, 4)}`).join(", ")
    }.`,
    "",
    "| Ordinal | Blob | Called as | Since | Bytes | Stack | Ending stack |",
    "| ---: | --- | --- | ---: | ---: | ---: | ---: |",
  ];
  let bytes = 0;
  for (const h of built.helpers) {
    const as = basieNames.get(h.ordinal);
    const called = as
      ? `\`${as}\``
      : h.convention === 1
      ? "service"
      : "register helper";
    out.push(
      `| ${
        hex(h.ordinal, 3)
      } | \`${h.name}\` | ${called} | ${h.since} | ${h.size} | ${h.returning} | ${h.ending} |`,
    );
    bytes += h.size;
  }
  out.push(
    "",
    `${built.helpers.length} helpers, ${bytes} bytes; the largest ending stack is ${
      Math.max(...built.helpers.map((h) => h.ending))
    } bytes.`,
    "",
    END,
  );
  return out.join("\n");
}

/** docs/helper-table.md with its generated section replaced. */
export function updateDoc(doc: string, section: string): string {
  const i = doc.indexOf(BEGIN);
  const j = doc.indexOf(END);
  if (i < 0 || j < 0) {
    throw new Error("helper-table.md has no generated section");
  }
  return doc.slice(0, i) + section + doc.slice(j + END.length);
}

/** Basie names of the services, by ordinal. */
export async function serviceNames(): Promise<Map<number, string>> {
  const { SERVICES } = await import("../ref/compile/helpers.ts");
  return new Map(SERVICES.map((s) => [s.ordinal, s.name]));
}

if (import.meta.main) {
  const built = await buildRuntime();
  await Deno.writeTextFile(MODULE, helperModule(built));
  await Deno.writeTextFile(NATIVE, nativeHelpers(built));
  await Deno.writeTextFile(NAMES, nativeNames(built));
  await Deno.writeTextFile(IOERRS, ioErrorLengths());
  const doc = await Deno.readTextFile(DOC);
  await Deno.writeTextFile(
    DOC,
    updateDoc(doc, helperTables(built, await serviceNames())),
  );
  console.log(
    `${built.helpers.length} helpers; ref/compile/helper-table.ts, native/compiler/HELPERS.ASM, PREDEF.ASM and IOERRS.ASM and docs/helper-table.md updated`,
  );
}
